### ISSUE TITLE
HDMI works but no sound output

### ISSUE THREAD

**Issue by marshalltoshady** [quzard/m720q-hackintosh#2]
I successfully connect a monitor with HDMI, but when I choose Digital out put(HDMI), there is no sound output.

If I choose Inside speaker, it works fine.

Hope u can help me, thanks a lot!!!

**Comment by quzard** [comment]
Does your monitor have speakers ?

**Comment by marshalltoshady** [comment]
Hi, 

Thanks your reply! Your work is brilliant.

I solve the problem, the problem is in your config.plist you enabled VoodooHDA.kext, I think it conflict with APPLEALC. You need to disable this kext in your config.plist file, when I disable it, everything is fine, thanks!

<dict>
				<key>Arch</key>
				<string>Any</string>
				<key>BundlePath</key>
				<string>VoodooHDA.kext</string>
				<key>Comment</key>
				<string></string>
				<key>_**Enabled**_</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoodooHDA</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

**Comment by marshalltoshady** [comment]
I think some people may meet the same issue with me, if you can disbale it in your config.plist, it will be so good!

**Comment by quzard** [comment]
> I think some people may meet the same issue with me, if you can disbale it in your config.plist, it will be so good!

I will change it. Thanks
